### ISSUE TITLE
UMD bundles not working in AoT mode

### ISSUE THREAD

**Issue by karlhaas** [zefoy/ngx-color-picker#2]
See https://github.com/Alberplz/angular2-color-picker/pull/72#issuecomment-279212400
```
Error: Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol Injectable in projectdir/node_modules/ngx-color-picker/node_modules/@angular/core/src/di/metadata.d.ts, resolving symbol OpaqueToken in projectdir/node_modules/ngx-color-picker/node_modules/@angular/core/src/di/opaque_token.d.ts, resolving symbol OpaqueToken in projectdir/node_modules/ngx-color-picker/node_modules/@angular/core/src/di/opaque_token.d.ts
    at SyntaxError.BaseError [as constructor] (projectdir/node_modules/@angular/compiler/bundles/compiler.umd.js:1597:31)
    at new SyntaxError (projectdir/node_modules/@angular/compiler/bundles/compiler.umd.js:1795:20)
    at simplifyInContext (projectdir/node_modules/@angular/compiler/bundles/compiler.umd.js:25783:27)
    at StaticReflector.simplify (projectdir/node_modules/@angular/compiler/bundles/compiler.umd.js:25795:17)
    at StaticReflector.annotations (projectdir/node_modules/@angular/compiler/bundles/compiler.umd.js:25291:64)
    at NgModuleResolver.resolve (projectdir/node_modules/@angular/compiler/bundles/compiler.umd.js:17771:86)
    at CompileMetadataResolver.getNgModuleMetadata (projectdir/node_modules/@angular/compiler/bundles/compiler.umd.js:18272:64)
    at addNgModule (projectdir/node_modules/@angular/compiler/bundles/compiler.umd.js:25053:62)
    at projectdir/node_modules/@angular/compiler/bundles/compiler.umd.js:25064:18
    at Array.forEach (native)
Compilation failed


```

**Comment by karlhaas** [comment]
Maybe the issue is caused by using npm link. https://github.com/angular/angular-cli/issues/3854.

**Comment by sconix** [comment]
Why would you be using umd bundle with AoT? Afaik umd bundles are usually for systemJS etc. For AOT you need the metadata files which are not provided by umd bundle directory. So for AOT build you should use the library from the lib directory.

**Comment by karlhaas** [comment]
We are using SystemJS and we are using just the UMD bundles for some other libraries. Maybe it was just an issue caused by npm link. I will close the issue because we switched to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color

**Comment by sconix** [comment]
Ok, I think so as well that it was npm link. I recall seeing something similar at some point.
