### ISSUE TITLE
build --prod error:  Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by bborad** [zefoy/ngx-color-picker#220]
Hi 

i am using this in Ionic 4/Angular app. All works fine in dev build but when I try to create prod build for android, i am getting this error.

ERROR in ./node_modules/ngx-color-picker/fesm5/ngx-color-picker.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
TypeError: Cannot read property 'kind' of undefined
    at isAngularDecoratorMetadataExpression (C:\Users\Levo\Docs\my\ionic\expensetracker\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:265:35)
    at checkNodeForDecorators (C:\Users\Levo\Docs\my\ionic\expensetracker\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:77:21)
    at visitNodes (C:\Users\Levo\Docs\my\ionic\expensetracker\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16144:30)
    at Object.forEachChild (C:\Users\Levo\Docs\my\ionic\expensetracker\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:16370:24)
    at checkNodeForDecorators (C:\Users\Levo\Docs\my\ionic\expensetracker\node_modules\@angular-devkit\build-optimizer\src\transforms\scrub-file.js:68:31)
. . . . 
. . . . 
[ERROR] An error occurred while running subprocess ng.

Any idea what could be causing this?

Thanks

**Comment by dprandzioch** [comment]
Same here in a plain Angular 8 project... Any ideas?

**Comment by Crocsx** [comment]
Isn't this the same as https://github.com/zefoy/ngx-color-picker/issues/218

**Comment by DamianDugan** [comment]
Not a proper fix, but downgrading to version 8.2.0 solved it for me.

npm install ngx-color-picker@8.2.0

**Comment by bborad** [comment]
now getting diff error

![image](https://user-images.githubusercontent.com/4285840/75598295-66174380-5ae6-11ea-96eb-e6f05a84b573.png)

**Comment by ankit1329** [comment]
Getting the same error on ng build --prod

**Comment by ankit1329** [comment]
I can confirm v7.5.0 doesn't have this issue with Angular 7. v8.20 should work with Angular 8 though I haven't tested it.
If this is the case then maybe this should be mentioned in the docs.

**Comment by davidk85** [comment]
Getting the same error on ssr build with angular 8 (devkit ^0.801.3). Downgrade to 8.2.0 from 9.x works for me.
