### ISSUE TITLE
error while AOT compilaton

### ISSUE THREAD

**Issue by ShermanT** [zefoy/ngx-color-picker#64]
i am getting this error while AOT compilation
```
admin1@PC-131:/home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public$ npm run build:aot
> angular-starter@6.0.0 build:aot /home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public
> npm run build:aot:prod


> angular-starter@6.0.0 build:aot:prod /home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public
> npm run clean:dist && npm run clean:aot && cross-env BUILD_AOT=1 npm run webpack -- --config config/webpack.prod.js  --progress --profile --bail


> angular-starter@6.0.0 clean:dist /home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public
> npm run rimraf -- dist


> angular-starter@6.0.0 rimraf /home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public
> rimraf "dist"


> angular-starter@6.0.0 clean:aot /home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public
> npm run rimraf -- compiled


> angular-starter@6.0.0 rimraf /home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public
> rimraf "compiled"


> angular-starter@6.0.0 webpack /home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public
> node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"

fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
Starting compilation using the angular compiler.
Angular compilation done, starting webpack bundling.
Error: Child compilation failed:
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (/home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public/node_modules/extract-text-webpack-plugin/loader.js:25:9):
Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at /home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public/node_modules/src/webpack-resource-loader.ts:66:18
    at Compiler.<anonymous> (/home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public/node_modules/webpack/lib/Compiler.js:296:10)
    at /home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public/node_modules/webpack/lib/Compiler.js:499:13
    at next (/home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public/node_modules/tapable/lib/Tapable.js:138:11)
    at Compiler.<anonymous> (/home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public/node_modules/webpack/lib/CachePlugin.js:62:5)
    at Compiler.applyPluginsAsyncSeries (/home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public/node_modules/tapable/lib/Tapable.js:142:13)
    at /home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public/node_modules/webpack/lib/Compiler.js:496:10
    at Compilation.applyPluginsAsyncSeries (/home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public/node_modules/tapable/lib/Tapable.js:131:46)
    at self.applyPluginsAsync.err (/home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public/node_modules/webpack/lib/Compilation.js:649:19)
    at Compilation.applyPluginsAsyncSeries (/home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public/node_modules/tapable/lib/Tapable.js:131:46)
    at self.applyPluginsAsync.err (/home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public/node_modules/webpack/lib/Compilation.js:640:11)
    at next (/home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public/node_modules/tapable/lib/Tapable.js:138:11)
    at Compilation.compilation.plugin (/home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:230:5)
    at Compilation.applyPluginsAsyncSeries (/home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public/node_modules/tapable/lib/Tapable.js:142:13)
    at self.applyPluginsAsync.err (/home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public/node_modules/webpack/lib/Compilation.js:635:10)
    at Compilation.applyPluginsAsyncSeries (/home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public/node_modules/tapable/lib/Tapable.js:131:46)
    at sealPart2 (/home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public/node_modules/webpack/lib/Compilation.js:631:9)
    at Compilation.applyPluginsAsyncSeries (/home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public/node_modules/tapable/lib/Tapable.js:131:46)
    at Compilation.seal (/home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public/node_modules/webpack/lib/Compilation.js:579:8)
    at /home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public/node_modules/webpack/lib/Compiler.js:493:16
    at /home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public/node_modules/tapable/lib/Tapable.js:225:11
    at _addModuleChain (/home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public/node_modules/webpack/lib/Compilation.js:481:11)
    at processModuleDependencies.err (/home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public/node_modules/webpack/lib/Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

npm ERR! Linux 4.4.0-93-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "webpack" "--" "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! angular-starter@6.0.0 webpack: `node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-starter@6.0.0 webpack script 'node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "config/webpack.prod.js" "--progress" "--profile" "--bail"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public/npm-debug.log

npm ERR! Linux 4.4.0-93-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:aot:prod"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! angular-starter@6.0.0 build:aot:prod: `npm run clean:dist && npm run clean:aot && cross-env BUILD_AOT=1 npm run webpack -- --config config/webpack.prod.js  --progress --profile --bail`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-starter@6.0.0 build:aot:prod script 'npm run clean:dist && npm run clean:aot && cross-env BUILD_AOT=1 npm run webpack -- --config config/webpack.prod.js  --progress --profile --bail'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean:dist && npm run clean:aot && cross-env BUILD_AOT=1 npm run webpack -- --config config/webpack.prod.js  --progress --profile --bail
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public/npm-debug.log

npm ERR! Linux 4.4.0-93-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build:aot"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! angular-starter@6.0.0 build:aot: `npm run build:aot:prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-starter@6.0.0 build:aot script 'npm run build:aot:prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:aot:prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-starter
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home1/lamppp/htdocs/gekko123/gekko_webpack_demo/GekkoWorks/public/npm-debug.log

```

**Comment by Destreyf** [comment]
This error doesn't appear to point at the color picker specifically, can you run `ng -v` and paste the results.

I am running angular@4.4.3 and ngx-color-picker@4.3.4  Can you also run `npm list | grep ngx-color` to list the version of the color picker installed?

**Comment by dbettini** [comment]
Check [this](https://github.com/zefoy/ngx-color-picker/issues/65#issuecomment-334470186)

**Comment by sconix** [comment]
Closing as duplicate, there is more discussion in the #65
